const SESSIONS = [
  {
    id: 1,
    name: "DINÁMICA II - CIENCIAS",
    program: "PREICFES INTENSIVO SG",
    date: "2026-02-03",
    time: "8:04 p.m. - 10:16 p.m.",
    students: [
      ["danna valentina salazar avirama","","dann************@***.com","8 min","8:04 p.m.","8:12 p.m."],
      ["SG - DIANA CAROLINA RUIZ","","ruiz*********@***.com","1 h 43 min","8:19 p.m.","10:02 p.m."],
      ["IETAC - MARÍA ESTHER","ACOSTA FERIA","acos****************@***.com","1 h 33 min","8:42 p.m.","10:16 p.m."],
      ["SG - ANGELA VIVIANA","ACOSTA PERAFAN","acos******************@***.com","1 h 20 min","8:15 p.m.","9:35 p.m."],
      ["SG - JOSIAS","ACUÑA ARIAS","acun**************@***.com","18 min","8:10 p.m.","10:15 p.m."],
      ["Yamir","Alejandro","yami*************@***.com","2 h 10 min","8:05 p.m.","10:15 p.m."],
      ["IETAC - CAMILO ANDRÉS","ARROYO CASTRO","arro*****************@***.com","41 min","9:01 p.m.","9:42 p.m."],
      ["SG - VALERIA","AUSECHA CAMPO","ause****************@***.com","2 h 8 min","8:07 p.m.","10:15 p.m."],
      ["SG - MIGUEL ANGEL","AYALA PRIETO","ayal****************@***.com","16 min","8:10 p.m.","8:26 p.m."],
      ["IETAC - JAIRO MANUEL","BALTAZAR VILLERO","balt********************@***.com","1 h 52 min","8:08 p.m.","9:59 p.m."],
      ["SG - SARA MILETH","BALVIN ARIAS","balv****************@***.com","2 h 11 min","8:04 p.m.","10:15 p.m."],
      ["IETAC - ANA BELÉN","BARÓN CEBALLOS","baro******************@***.com","1 h 51 min","8:17 p.m.","10:16 p.m."],
      ["IETAC - LUISA FERNANDA","BARÓN LUCAS","baro***************@***.com","2 h 9 min","8:05 p.m.","10:16 p.m."],
      ["SG - YEIMI PAOLA","BARRAGAN BABILONIA","barr**********************@***.com","2 h 6 min","8:07 p.m.","10:14 p.m."],
      ["SG - ISABELA","BARREIRO CÁRDENAS","barr*******************@***.com","2 h 10 min","8:04 p.m.","10:14 p.m."],
      ["IETAC - MARIANA DE JESÚS","CABADIA PARRA","caba*****************@***.com","1 h 37 min","8:38 p.m.","10:16 p.m."],
      ["SG - KIARA","CALDERA CORONADO","cald*******************@***.com","2 h 10 min","8:06 p.m.","10:15 p.m."],
      ["SG - HILAYDA ROSA","CANTILLO RUZ","cant****************@***.com","2 h 9 min","8:06 p.m.","10:15 p.m."],
      ["SG - MARIA PAULA","CARBALLO QUINTERO","carb******************@***.com","2 h 7 min","8:09 p.m.","10:16 p.m."],
      ["Matias","CardenasLozano","maty*******@***.com","1 h 20 min","8:09 p.m.","9:29 p.m."],
      ["SG - MARÍA JULIETH","CASTILLO BAUTISTA","sg.e***********************@***.com","1 h 23 min","8:52 p.m.","10:16 p.m."],
      ["SG - CARLOS ANDRÉS","CHARRIS BONETT","char******************@***.com","1 h 25 min","8:17 p.m.","9:57 p.m."],
      ["Daginve","Collazos Trujillo","coll********************@***.com","2 min","8:04 p.m.","8:06 p.m."],
      ["IETAC - NEIVER","CORDOBA ARGUMEDO","cord*******************@***.com","1 h 57 min","8:07 p.m.","10:04 p.m."],
      ["IETAC - JUAN DAVID","CORREA HERNÁNDEZ","corr********************@***.com","1 h 40 min","8:14 p.m.","9:54 p.m."],
      ["SG - MARÍA JOSÉ","CORTES CHALITAS","cort*******************@***.com","43 min","8:28 p.m.","9:12 p.m."],
      ["SG - CRISTIAN DE JESUS","CUESTA BLANQUICETT","cues******************@***.com","2 h 6 min","8:10 p.m.","10:15 p.m."],
      ["DANIEL CAMILO","CUSPOCA QUITIAN","dani**************************@***.com","2 h 19 min","7:57 p.m.","10:16 p.m."],
      ["SG - SAMUEL","DIAZ HOYOS","samu******************@***.com","1 h 52 min","8:15 p.m.","10:16 p.m."],
      ["SG - MARIANA","DÍAZ ZÚÑIGA","diaz**************@***.com","1 h 27 min","8:37 p.m.","10:15 p.m."],
      ["SG - JUAN ANDRES","ECHEVERRÍA ESCOBAR","eche********************@***.com","47 min","8:07 p.m.","8:54 p.m."],
      ["SG - LUIS FELIPE","ESCUDERO VILLEGAS","escu*******************@***.com","5 min","9:06 p.m.","9:11 p.m."],
      ["SG - SARA SOFIA","ESQUIVEL VARGAS","esqu*******************@***.com","2 h 11 min","8:04 p.m.","10:15 p.m."],
      ["SG-TALIANA ANDREA","FLOREZ SALGADO","flor******************@***.com","50 min","8:05 p.m.","8:55 p.m."],
      ["SG - VALERIE","GAMARRA FONTALVO","gama*******************@***.com","2 h 6 min","8:10 p.m.","10:15 p.m."],
      ["SG - LAURA MADELEINE","GÓMEZ SUÁREZ","gome****************@***.com","1 h 19 min","8:09 p.m.","9:28 p.m."],
      ["SG - SOFÍA VALENTINA","GOYES VALLEJO","goye*****************@***.com","2 h 8 min","8:07 p.m.","10:16 p.m."],
      ["SG - ANGIE KATHERINE","GUERRERO CUARAN","guer*******************@***.com","2 h 9 min","8:06 p.m.","10:16 p.m."],
      ["SG - MARIA JOSE","GUTIERREZ OSORIO","guti******************@***.com","2 h 4 min","8:08 p.m.","10:12 p.m."],
      ["SG - MATHIAS JOSÉ","HERNÁNDEZ BERMÚDEZ","hern********************@***.com","1 h 6 min","8:57 p.m.","10:03 p.m."],
      ["SG - ADRIANA ISABEL","HOYOS HOYOS","hoyo***************@***.com","41 min","8:16 p.m.","8:57 p.m."],
      ["IETAC - Harold Iván","Hoyos Vergara","hoyo*****************@***.com","2 h 6 min","8:10 p.m.","10:16 p.m."],
      ["SG - EMMA ISABELLA","LINDADO ALGARIN","lind*******************@***.com","2 h 12 min","8:04 p.m.","10:16 p.m."],
      ["SG - SAMUEL","LOAIZA ZAMBRANO","loai******************@***.com","2 h 12 min","8:04 p.m.","10:16 p.m."],
      ["erika","luligo quira","erik***********@***.com","2 h 9 min","8:07 p.m.","10:16 p.m."],
      ["SG - DIANA MARCELA","MANBUSCAY AGUDELO","manb******************@***.com","2 h 9 min","8:06 p.m.","10:16 p.m."],
      ["SG - DANIELA","MANCHOLA TORRES","manc******************@***.com","1 h 18 min","8:04 p.m.","9:22 p.m."],
      ["SG-LEYSA LUZ","MARTINEZ MENDOZA","mart********************@***.com","1 h 8 min","8:10 p.m.","9:19 p.m."],
      ["SG - ROSA","MENDIETA FONSECA","mend******************@***.com","2 min","8:16 p.m.","8:18 p.m."],
      ["SG - JUAN PABLO","MONTOYA ZAPATA","mont******************@***.com","1 h 49 min","8:27 p.m.","10:16 p.m."],
      ["SG - NUBIA LISETH","MORA HERMOZO","mora*************@***.com","2 h 6 min","8:09 p.m.","10:15 p.m."],
      ["SG- SHAROL VANESSA","MORALES OSPINO","mora******************@***.com","52 min","8:05 p.m.","9:51 p.m."],
      ["IETAC - MARÍA ANGÉLICA","MORELO VILLEROS","more*******************@***.com","1 h 35 min","8:19 p.m.","9:54 p.m."],
      ["SG - SOFIA","MÚNERA LÓPEZ","mune***************@***.com","2 h 12 min","8:04 p.m.","10:16 p.m."],
      ["IETAC - YULEIMIS","MURILLO GÓMEZ","muri****************@***.com","2 h 3 min","8:12 p.m.","10:15 p.m."],
      ["SG - ANDRES FELIPE","OROZCO ARRIOLA","oroz******************@***.com","2 h 6 min","8:08 p.m.","10:13 p.m."],
      ["SG - LAURA SOFÍA","OVEJERO MALDONADO","over*********************@***.com","2 h 11 min","8:04 p.m.","10:16 p.m."],
      ["MARÍA PAULA","PÉREZ HORMIGA","pere*****************@***.com","6 min","8:08 p.m.","8:15 p.m."],
      ["IETAC - JORGE ANDRÉS","PÉREZ MESTRA","pere****************@***.com","1 h 24 min","8:08 p.m.","9:32 p.m."],
      ["SG - KEVIN SANTIAGO","PORTILLO BENAVIDES","port********************@***.com","2 h 3 min","8:10 p.m.","10:15 p.m."],
      ["SG - JAVIER SANTIAGO","PULIDO GONZALEZ","puli*******************@***.com","2 h 5 min","8:10 p.m.","10:16 p.m."],
      ["SG - CAMILA ALEJANDRA","RAMIREZ RUEDA","rami*****************@***.com","1 h 58 min","8:18 p.m.","10:15 p.m."],
      ["IETAC - DARY LUZ","RAMOS","ramo**********@***.com","2 h","8:15 p.m.","10:16 p.m."],
      ["SG - DANNA ALEJANDRA","RECALDE RODRÍGUEZ","reca*********************@***.com","30 min","8:07 p.m.","8:37 p.m."],
      ["SG - ROSA INES","REVEROL GONZALEZ","reve*******************@***.com","1 h 38 min","8:19 p.m.","9:57 p.m."],
      ["SG - MIGUEL ANDRÉS","RHENALS ARGUMEDO","rhen********************@***.com","2 h","8:05 p.m.","10:15 p.m."],
      ["SG - LAURA SOFIA","RIASCOS PANTOJA","rias*******************@***.com","1 h 14 min","8:08 p.m.","9:22 p.m."],
      ["COO - JESUS ALBERTO","RODRIGUEZ ORTEGA","jesu***************@***.com","8 min","9:16 p.m.","9:24 p.m."],
      ["IETAC - SHARON LISHELL","RODRIGUEZ OSORIO","rodr********************@***.com","53 min","9:22 p.m.","10:15 p.m."],
      ["IETAC - VIVIANA MARCELA","ROMERO ZÚÑIGA","rome*****************@***.com","2 h 10 min","8:06 p.m.","10:16 p.m."],
      ["SG - DANNA VALENTINA","SALAZAR AVIRAMA","sala*******************@***.com","1 h 59 min","8:14 p.m.","10:15 p.m."],
      ["IETAC - JOHAN ANDRÉS","SALCEDO BEDOYA","salc******************@***.com","2 h 6 min","8:07 p.m.","10:13 p.m."],
      ["Melany","Sánchez","mely***********@***.com","2 h 11 min","8:04 p.m.","10:16 p.m."],
      ["IETAC - DAINER ANDRÉS","SÁNCHEZ CASTRO","sanc******************@***.com","1 h 58 min","8:17 p.m.","10:16 p.m."],
      ["SG-VALENTINA","SANDOVAL DIAZ","sand****************@***.com","2 h 3 min","8:12 p.m.","10:15 p.m."],
      ["IETAC - ARNEDIS","SIBAJA BEGAMBRE","siba******************@***.com","1 h 58 min","8:09 p.m.","10:07 p.m."],
      ["SG-ALEX","SIERRA BENÍTEZ","sier*****************@***.com","2 h 10 min","8:05 p.m.","10:15 p.m."],
      ["SG-RAYLEE CRISTINA","SILVA","silv***************@***.com","2 h 9 min","8:05 p.m.","10:15 p.m."],
      ["Nestor Gabriel","Silva Bahamon","silv*****************@***.com","2 h 6 min","8:04 p.m.","10:10 p.m."],
      ["SG - JOSÉ ÁNGEL","SORA MERCHAN","sora****************@***.com","2 h 6 min","8:04 p.m.","10:10 p.m."],
      ["IETAC - SAMIR MANUEL","SUREZ ENSUNCHO","sure******************@***.com","1 h 51 min","8:25 p.m.","10:16 p.m."],
      ["SG - GABRIEL","SUTACHAN MENDEZ","suta******************@***.com","2 h 1 min","8:15 p.m.","10:15 p.m."],
      ["SG - ISABELLA","TAPIA ROMERO","tapi***************@***.com","1 h 16 min","8:08 p.m.","9:24 p.m."],
      ["SG - HANNA NICOLLE","TREJOS APACHE","trej*****************@***.com","2 h 10 min","8:05 p.m.","10:16 p.m."],
      ["SG - JOSE MIGUEL","URREA GÓMEZ","urre***************@***.com","2 h 11 min","8:05 p.m.","10:16 p.m."],
      ["SG - ISABELLA","VÁSQUEZ CASAS","vasq****************@***.com","1 h 45 min","8:30 p.m.","10:16 p.m."],
      ["IETAC - ELIANA MARCELA","VERGARA GANDIA","verg******************@***.com","1 h 49 min","8:14 p.m.","10:02 p.m."],
      ["SG - ISABEL","VILLEGAS ORTIZ","vill******************@***.com","14 min","8:10 p.m.","8:24 p.m."],
      ["IETAC - LUIS MARIO","ZABALA SÁNCHEZ","zaba******************@***.com","1 h 23 min","8:08 p.m.","9:34 p.m."],
      ["Ronaldo","Zuleta","rona*********************@***.com","47 min","8:11 p.m.","9:02 p.m."],
      ["IETAC - RONALDO ANDRÉS","ZULETA GUERRA","zule*****************@***.com","1 h 20 min","8:55 p.m.","10:16 p.m."]
    ]
  },
  {
    id: 2,
    name: "PRÁCTICA 9 - SOCIALES",
    program: "PREINTENSIVO - CAL B",
    date: "2026-02-05",
    time: "8:17 p.m. - 10:07 p.m.",
    students: [
      ["isa","","isab****************@***.com","5 s","8:17 p.m.","8:17 p.m."],
      ["SG - DIANA CAROLINA RUIZ","","ruiz*********@***.com","1 h 56 min","8:10 p.m.","10:06 p.m."],
      ["IETAC - MARÍA ESTHER","ACOSTA FERIA","acos****************@***.com","2 h","8:06 p.m.","10:06 p.m."],
      ["SG - ANGELA VIVIANA","ACOSTA PERAFAN","acos******************@***.com","2 h","8:07 p.m.","10:07 p.m."],
      ["SG - KAREN YULIED","ARENAS COMETA","aren*****************@***.com","1 h 56 min","8:10 p.m.","10:06 p.m."],
      ["IETAC - KAREN SOFÍA","ARRIETA VERGARA","arri*******************@***.com","2 h 2 min","8:03 p.m.","10:05 p.m."],
      ["IETAC - CAMILO ANDRÉS","ARROYO CASTRO","arro*****************@***.com","2 h 2 min","8:04 p.m.","10:07 p.m."],
      ["SG - VALERIA","AUSECHA CAMPO","ause****************@***.com","2 h 3 min","8:03 p.m.","10:06 p.m."],
      ["SG - SHEYLA DE JESUS","AVILEZ VEGA","avil***************@***.com","1 h 58 min","8:09 p.m.","10:07 p.m."],
      ["SG - MIGUEL ANGEL","AYALA PRIETO","ayal****************@***.com","1 h 41 min","8:05 p.m.","9:47 p.m."],
      ["IETAC - JAIRO MANUEL","BALTAZAR VILLERO","balt********************@***.com","1 h 27 min","8:05 p.m.","9:31 p.m."],
      ["SG - SARA MILETH","BALVIN ARIAS","balv****************@***.com","2 h 2 min","8:03 p.m.","10:06 p.m."],
      ["IETAC - LUISA FERNANDA","BARÓN LUCAS","baro***************@***.com","2 h","8:06 p.m.","10:07 p.m."],
      ["SG - YEIMI PAOLA","BARRAGAN BABILONIA","barr**********************@***.com","1 h 54 min","8:05 p.m.","10:00 p.m."],
      ["SG - ISABELA","BARREIRO CÁRDENAS","barr*******************@***.com","1 h 59 min","8:05 p.m.","10:04 p.m."],
      ["IETAC - MARIANA DE JESÚS","CABADIA PARRA","caba*****************@***.com","2 min","8:11 p.m.","8:13 p.m."],
      ["SG - KIARA","CALDERA CORONADO","cald*******************@***.com","2 h 4 min","8:03 p.m.","10:07 p.m."],
      ["Oscar Andres","Cano Sanchez","osca*********************@***.com","2 h","8:06 p.m.","10:06 p.m."],
      ["SG - HILAYDA ROSA","CANTILLO RUZ","cant****************@***.com","2 h 3 min","8:03 p.m.","10:06 p.m."],
      ["SG - MARIA PAULA","CARBALLO QUINTERO","carb******************@***.com","1 h 59 min","8:07 p.m.","10:06 p.m."],
      ["IETAC - KAREN DAYANA","CASTILLO PÉREZ","cast******************@***.com","2 h 3 min","8:03 p.m.","10:07 p.m."],
      ["SG - CARLOS ANDRÉS","CHARRIS BONETT","char******************@***.com","1 h 52 min","8:10 p.m.","10:06 p.m."],
      ["SG - JULIAN ESTIBEN","CHIVATA OTALORA","chiv*******************@***.com","7 min","10:00 p.m.","10:07 p.m."],
      ["IETAC - NEIVER","CORDOBA ARGUMEDO","cord*******************@***.com","1 h 19 min","8:48 p.m.","10:07 p.m."],
      ["IETAC - JUAN DAVID","CORREA HERNÁNDEZ","corr********************@***.com","2 h 4 min","8:02 p.m.","10:06 p.m."],
      ["SG - MARÍA JOSÉ","CORTES CHALITAS","cort*******************@***.com","1 h 8 min","8:10 p.m.","9:19 p.m."],
      ["samuel","diaz hoyos","samu********************@***.com","34 min","8:09 p.m.","8:43 p.m."],
      ["SG - SAMUEL","DIAZ HOYOS","samu******************@***.com","52 min","8:43 p.m.","9:41 p.m."],
      ["SG - SALOMÉ","DIAZ VALENCIA","diaz****************@***.com","1 h 27 min","8:06 p.m.","9:33 p.m."],
      ["SG - MARIANA","DÍAZ ZÚÑIGA","diaz**************@***.com","1 h 40 min","8:27 p.m.","10:07 p.m."],
      ["IETAC - JHOANS SEBASTIAN","DURANGO ZABALA","dura******************@***.com","2 h 4 min","8:02 p.m.","10:06 p.m."],
      ["SG - JUAN ANDRES","ECHEVERRÍA ESCOBAR","eche********************@***.com","1 h 37 min","8:07 p.m.","9:44 p.m."],
      ["Christopher","Erazo","chri******************@***.com","1 h 46 min","8:06 p.m.","10:07 p.m."],
      ["SG - LUIS FELIPE","ESCUDERO VILLEGAS","escu*******************@***.com","1 h 48 min","8:18 p.m.","10:06 p.m."],
      ["SG - SARA SOFIA","ESQUIVEL VARGAS","esqu*******************@***.com","2 h 3 min","8:04 p.m.","10:07 p.m."],
      ["SG - CRISTIAN DAVID","FAJARDO PERILLA","faja*******************@***.com","1 h","8:03 p.m.","9:07 p.m."],
      ["SG - DANIELA SOFÍA","FLOREZ VARGAS","flor*****************@***.com","25 min","8:02 p.m.","8:36 p.m."],
      ["SG - VALERIE","GAMARRA FONTALVO","gama*******************@***.com","2 h","8:05 p.m.","10:05 p.m."],
      ["SG - ÁNGEL GABRIEL","GÓMEZ","gome**********@***.com","1 h 40 min","8:06 p.m.","9:46 p.m."],
      ["SG - SOFÍA VALENTINA","GOYES VALLEJO","goye*****************@***.com","1 h 20 min","8:11 p.m.","9:31 p.m."],
      ["SG - MARIA JOSE","GUTIERREZ OSORIO","guti******************@***.com","1 h 49 min","8:18 p.m.","10:07 p.m."],
      ["SG - LAURA CAMILA","GUZMÁN LÓPEZ","guzm****************@***.com","2 h 2 min","8:03 p.m.","10:06 p.m."],
      ["SG - KAMILA INES","HERRERA MARTINEZ","herr*******************@***.com","1 h 56 min","8:10 p.m.","10:06 p.m."],
      ["IETAC - Harold Iván","Hoyos Vergara","hoyo*****************@***.com","2 h 3 min","8:04 p.m.","10:06 p.m."],
      ["IETAC - ALEXANDRA","JULIO ROMERO","juli***************@***.com","54 min","8:07 p.m.","9:01 p.m."],
      ["SG - JHOAN DAVID","LEÓN LAGOS","leon**************@***.com","42 min","8:29 p.m.","9:10 p.m."],
      ["SG - EMMA ISABELLA","LINDADO ALGARIN","lind*******************@***.com","2 h 5 min","8:00 p.m.","10:06 p.m."],
      ["SG - SAMUEL","LOAIZA ZAMBRANO","loai******************@***.com","2 h","8:06 p.m.","10:06 p.m."],
      ["SG - ALEJANDRO DAVID","LORA TORRES","lora**************@***.com","1 h 33 min","8:04 p.m.","9:59 p.m."],
      ["erika","luligo quira","erik***********@***.com","41 min","8:02 p.m.","8:43 p.m."],
      ["SG - DIANA MARCELA","MANBUSCAY AGUDELO","manb******************@***.com","2 h 4 min","8:03 p.m.","10:07 p.m."],
      ["IETAC - ISABELLA","MANCHEGO LOZANO","manc******************@***.com","1 h 45 min","8:17 p.m.","10:07 p.m."],
      ["SG - NIKOL VANESSA","MANCILLA GONZALEZ","manc*********************@***.com","10 s","8:17 p.m.","8:17 p.m."],
      ["SG-LEYSA LUZ","MARTINEZ MENDOZA","mart********************@***.com","2 h 3 min","8:03 p.m.","10:07 p.m."],
      ["SG - ROSA","MENDIETA FONSECA","mend******************@***.com","2 h 2 min","8:05 p.m.","10:07 p.m."],
      ["SG - MAVI SOFIA","MICOLTA CARABALI","mico*********************@***.com","34 min","8:06 p.m.","8:40 p.m."],
      ["SG - JUAN PABLO","MONTOYA ZAPATA","mont******************@***.com","1 h 59 min","8:07 p.m.","10:07 p.m."],
      ["SG - NUBIA LISETH","MORA HERMOZO","mora*************@***.com","2 h 1 min","8:06 p.m.","10:07 p.m."],
      ["SG- SHAROL VANESSA","MORALES OSPINO","mora******************@***.com","56 min","8:08 p.m.","9:09 p.m."],
      ["SG - SOFIA","MÚNERA LÓPEZ","mune***************@***.com","2 h 1 min","8:05 p.m.","10:07 p.m."],
      ["SG - LUIS ANTONIO","MUÑOZ HINCAPIE","muno******************@***.com","2 h 5 min","8:02 p.m.","10:07 p.m."],
      ["IETAC - YULEIMIS","MURILLO GÓMEZ","muri****************@***.com","1 h 59 min","8:07 p.m.","10:06 p.m."],
      ["CARLOS ALBERTO","MURILLO RANGEL","carl**********************@***.com","2 h 10 min","7:56 p.m.","10:07 p.m."],
      ["SG - ANDRES FELIPE","OROZCO ARRIOLA","oroz******************@***.com","1 h 59 min","8:07 p.m.","10:07 p.m."],
      ["IETAC - DAYANA MICHEL","PEÑA TORDECILLA","sg.e*********************@***.com","2 h 1 min","8:05 p.m.","10:06 p.m."],
      ["MARÍA PAULA","PÉREZ HORMIGA","pere*****************@***.com","8 min","8:19 p.m.","8:29 p.m."],
      ["SG - MARÍA PAULA","PÉREZ HORMIGA","sg.e**********************@***.com","1 h 10 min","8:29 p.m.","9:39 p.m."],
      ["SG - KEVIN SANTIAGO","PORTILLO BENAVIDES","port********************@***.com","1 h 56 min","8:09 p.m.","10:05 p.m."],
      ["SG - JULIO","PRADO BARRIOS","prad****************@***.com","1 h 58 min","8:02 p.m.","10:06 p.m."],
      ["SG - MARGREYS","QUINTERO PALOMINO","quin********************@***.com","2 h","8:06 p.m.","10:06 p.m."],
      ["camila","ramirez","cami************@***.com","32 min","8:11 p.m.","8:43 p.m."],
      ["SG - CAMILA ALEJANDRA","RAMIREZ RUEDA","rami*****************@***.com","1 h 21 min","8:45 p.m.","10:06 p.m."],
      ["IETAC - DARY LUZ","RAMOS","ramo**********@***.com","2 h","8:06 p.m.","10:07 p.m."],
      ["SG - DANNA ALEJANDRA","RECALDE RODRÍGUEZ","reca*********************@***.com","1 h 35 min","8:15 p.m.","9:50 p.m."],
      ["SG - ROSA INES","REVEROL GONZALEZ","reve*******************@***.com","2 h","8:06 p.m.","10:06 p.m."],
      ["SG - MIGUEL ANDRÉS","RHENALS ARGUMEDO","rhen********************@***.com","2 h 3 min","8:03 p.m.","10:06 p.m."],
      ["SG - LAURA SOFIA","RIASCOS PANTOJA","rias*******************@***.com","2 h 1 min","8:05 p.m.","10:07 p.m."],
      ["SG - LORENA ANDREA","RODRÍGUEZ MARTÍNEZ","rodr**********************@***.com","19 min","9:04 p.m.","9:23 p.m."],
      ["IETAC - YULISA","RODRÍGUEZ RODRÍGUEZ","rodr**********************@***.com","1 h 25 min","8:03 p.m.","9:30 p.m."],
      ["IETAC - ADRIANA LUCÍA","ROJAS CORDERO","roja*****************@***.com","1 h 53 min","8:10 p.m.","10:07 p.m."],
      ["SG - DULCE MARÍA","ROJAS TARAZONA","roja******************@***.com","48 min","8:11 p.m.","8:59 p.m."],
      ["IETAC - VIVIANA MARCELA","ROMERO ZÚÑIGA","rome*****************@***.com","2 h","8:06 p.m.","10:07 p.m."],
      ["SG - YESSICA PAOLA","RUIZ RUIZ","ruiz*************@***.com","1 h 32 min","8:35 p.m.","10:07 p.m."],
      ["SG - DANNA VALENTINA","SALAZAR AVIRAMA","sala*******************@***.com","2 h","8:06 p.m.","10:06 p.m."],
      ["IETAC - JOHAN ANDRÉS","SALCEDO BEDOYA","salc******************@***.com","1 h 55 min","8:10 p.m.","10:06 p.m."],
      ["Melany","Sánchez","mely***********@***.com","2 h 1 min","8:06 p.m.","10:07 p.m."],
      ["IETAC - DAINER ANDRÉS","SÁNCHEZ CASTRO","sanc******************@***.com","4 min","8:14 p.m.","8:18 p.m."],
      ["SG-VALENTINA","SANDOVAL DIAZ","sand****************@***.com","2 h","8:05 p.m.","10:06 p.m."],
      ["SG - MARÍA FERNANDA","SANTANA RAMÍREZ","sant*******************@***.com","59 min","8:03 p.m.","9:02 p.m."],
      ["PREINTENSIVO","SEAMOSGENIOS","seamosgenios@adpmh.com","16 s","8:29 p.m.","8:30 p.m."],
      ["IETAC - ARNEDIS","SIBAJA BEGAMBRE","siba******************@***.com","2 h","8:06 p.m.","10:07 p.m."],
      ["SG-ALEX","SIERRA BENÍTEZ","sier*****************@***.com","1 h 59 min","8:07 p.m.","10:06 p.m."],
      ["SG - JOSÉ ÁNGEL","SORA MERCHAN","sora****************@***.com","2 h 2 min","8:03 p.m.","10:06 p.m."],
      ["SG - ANGIE CAROLINA","SOTO GIRALDO","soto****************@***.com","2 h 6 min","8:00 p.m.","10:07 p.m."],
      ["SG - GABRIEL","SUTACHAN MENDEZ","suta******************@***.com","2 h 1 min","8:05 p.m.","10:06 p.m."],
      ["SG - ISABELLA","TAPIA ROMERO","tapi***************@***.com","1 h 58 min","8:07 p.m.","10:06 p.m."],
      ["SG - HANNA NICOLLE","TREJOS APACHE","trej*****************@***.com","2 h","8:05 p.m.","10:06 p.m."],
      ["SG - JOSE MIGUEL","URREA GÓMEZ","urre***************@***.com","2 h 3 min","8:04 p.m.","10:07 p.m."],
      ["IETAC—ALEXANDRA","URZOLA MARTÍNEZ","urzo******************@***.com","1 h 44 min","8:23 p.m.","10:07 p.m."],
      ["SG - ISABELLA","VÁSQUEZ CASAS","vasq****************@***.com","1 h 49 min","8:18 p.m.","10:07 p.m."],
      ["IETAC - ELIANA MARCELA","VERGARA GANDIA","verg******************@***.com","2 h","8:06 p.m.","10:07 p.m."],
      ["SG - ISABEL","VILLEGAS ORTIZ","vill******************@***.com","13 min","8:06 p.m.","8:19 p.m."],
      ["IETAC - DANIEL ANDRÉS","ZABALA MONTIEL","zaba******************@***.com","1 h","8:20 p.m.","9:21 p.m."],
      ["IETAC - LUIS MARIO","ZABALA SÁNCHEZ","zaba******************@***.com","1 h 34 min","8:18 p.m.","10:06 p.m."],
      ["SG - JUAN DIEGO","ZAMBRANO OCAMPO","zamb*******************@***.com","2 h 1 min","8:04 p.m.","10:06 p.m."],
      ["IETAC - RONALDO ANDRÉS","ZULETA GUERRA","zule*****************@***.com","1 h 56 min","8:11 p.m.","10:07 p.m."]
    ]
  },
  {
    id: 3,
    name: "TALLER 6 - INGLÉS",
    program: "PREICFES INTENSIVO SG",
    date: "2026-01-20",
    time: "2:06 p.m. - 3:49 p.m.",
    students: [
      ["danna valentina salazar avirama","","dann************@***.com","1 h 43 min","2:06 p.m.","3:49 p.m."],
      ["Valerie Gamarra","","vale**********@***.com","1 h 33 min","2:15 p.m.","3:48 p.m."],
      ["IETAC - MARÍA ESTHER","ACOSTA FERIA","acos****************@***.com","1 h 47 min","2:01 p.m.","3:49 p.m."],
      ["SG - ANGELA VIVIANA","ACOSTA PERAFAN","acos******************@***.com","1 h 8 min","2:12 p.m.","3:20 p.m."],
      ["SG - KAREN YULIED","ARENAS COMETA","aren*****************@***.com","34 min","2:01 p.m.","2:35 p.m."],
      ["IETAC - XIMENA","ARIAS MANCO","aria**************@***.com","1 h 47 min","2:02 p.m.","3:49 p.m."],
      ["SG - VALERIA","AUSECHA CAMPO","ause****************@***.com","1 h 43 min","2:04 p.m.","3:47 p.m."],
      ["SG - SHEYLA DE JESUS","AVILEZ VEGA","avil***************@***.com","1 h 43 min","2:05 p.m.","3:49 p.m."],
      ["SG - MIGUEL ANGEL","AYALA PRIETO","ayal****************@***.com","1 h 24 min","2:24 p.m.","3:48 p.m."],
      ["IETAC - ANA BELÉN","BARÓN CEBALLOS","baro******************@***.com","1 h 14 min","2:17 p.m.","3:31 p.m."],
      ["IETAC - LUISA FERNANDA","BARÓN LUCAS","baro***************@***.com","1 h 42 min","2:06 p.m.","3:49 p.m."],
      ["SG - ISABELA","BARREIRO CÁRDENAS","barr*******************@***.com","8 s","2:18 p.m.","2:18 p.m."],
      ["SG - JULIANA","BORJA BUELVAS","borj****************@***.com","1 h 46 min","2:01 p.m.","3:47 p.m."],
      ["IETAC - MARIANA DE JESÚS","CABADIA PARRA","caba*****************@***.com","1 h 42 min","2:07 p.m.","3:49 p.m."],
      ["SG - KIARA","CALDERA CORONADO","cald*******************@***.com","1 h 31 min","2:14 p.m.","3:49 p.m."],
      ["SG - HILAYDA ROSA","CANTILLO RUZ","cant****************@***.com","1 h 44 min","2:05 p.m.","3:48 p.m."],
      ["SG - MARIA PAULA","CARBALLO QUINTERO","carb******************@***.com","1 h 46 min","2:03 p.m.","3:49 p.m."],
      ["Samara","Caro","sama**********@***.com","37 min","2:15 p.m.","2:52 p.m."],
      ["Natalia","Carvajal Vergara","nata*********@***.com","58 min","2:35 p.m.","3:43 p.m."],
      ["SG - MARÍA JULIETH","CASTILLO BAUTISTA","sg.e***********************@***.com","1 h 11 min","2:37 p.m.","3:49 p.m."],
      ["IETAC - KAREN DAYANA","CASTILLO PÉREZ","cast******************@***.com","30 min","3:19 p.m.","3:49 p.m."],
      ["Janer","Castro","jane******@***.com","52 min","2:33 p.m.","3:25 p.m."],
      ["Nicol","Cerpa","nico********@***.com","31 min","3:07 p.m.","3:38 p.m."],
      ["IETAC - JUAN DAVID","CORREA HERNÁNDEZ","corr********************@***.com","1 h 47 min","2:02 p.m.","3:49 p.m."],
      ["SG - MARÍA JOSÉ","CORTES CHALITAS","cort*******************@***.com","1 h 41 min","2:07 p.m.","3:48 p.m."],
      ["CAMILO ANDRES","COTES","cote*****@***.com","12 min","3:13 p.m.","3:26 p.m."],
      ["samuel","diaz hoyos","samu********************@***.com","27 s","2:18 p.m.","3:24 p.m."],
      ["IETAC - JHOANS SEBASTIAN","DURANGO ZABALA","dura******************@***.com","1 h 31 min","2:16 p.m.","3:48 p.m."],
      ["Juan","Echeverría escobar","juan*******@***.com","17 min","2:01 p.m.","2:18 p.m."],
      ["SG - JUAN ANDRES","ECHEVERRÍA ESCOBAR","eche********************@***.com","1 h 29 min","2:19 p.m.","3:48 p.m."],
      ["SG - LUIS FELIPE","ESCUDERO VILLEGAS","escu*******************@***.com","1 h 35 min","2:11 p.m.","3:49 p.m."],
      ["SG - SARA SOFIA","ESQUIVEL VARGAS","esqu*******************@***.com","1 h 46 min","2:03 p.m.","3:49 p.m."],
      ["SG - CRISTIAN DAVID","FAJARDO PERILLA","faja*******************@***.com","1 h 46 min","2:02 p.m.","3:47 p.m."],
      ["Liz valeria","Gil hoyos","lizv**************@***.com","1 h 44 min","2:04 p.m.","3:48 p.m."],
      ["SG - ÁNGEL GABRIEL","GÓMEZ","gome**********@***.com","1 h 39 min","2:09 p.m.","3:48 p.m."],
      ["Laura","Gomez suarez","made**************@***.com","1 h 6 min","2:11 p.m.","3:17 p.m."],
      ["SG - LAURA MADELEINE","GÓMEZ SUÁREZ","gome****************@***.com","58 min","2:09 p.m.","3:17 p.m."],
      ["SG - MARIA JOSE","GUTIERREZ OSORIO","guti******************@***.com","1 h 46 min","2:02 p.m.","3:48 p.m."],
      ["SG - LAURA CAMILA","GUZMÁN LÓPEZ","guzm****************@***.com","20 min","2:16 p.m.","2:36 p.m."],
      ["SG MATHIAS JOSÉ","HERNÁNDEZ BERMÚDEZ","hern****************@***.com","1 h 47 min","2:01 p.m.","3:48 p.m."],
      ["SG - KAMILA INES","HERRERA MARTINEZ","herr*******************@***.com","1 h 39 min","2:09 p.m.","3:48 p.m."],
      ["SG - ADRIANA ISABEL","HOYOS HOYOS","hoyo***************@***.com","1 h 44 min","2:05 p.m.","3:48 p.m."],
      ["IETAC - Harold Iván","Hoyos Vergara","hoyo*****************@***.com","1 h 48 min","2:00 p.m.","3:49 p.m."],
      ["Jhoan David","Leon Lagos","leon*********@***.com","1 h 42 min","2:06 p.m.","3:48 p.m."],
      ["SG - EMMA ISABELLA","LINDADO ALGARIN","lind*******************@***.com","1 h 47 min","2:01 p.m.","3:48 p.m."],
      ["SG - SAMUEL","LOAIZA ZAMBRANO","loai******************@***.com","1 h 39 min","2:09 p.m.","3:48 p.m."],
      ["SG-KAREN GABRIELA","LOPEZ PEDROZO","lope******************@***.com","59 min","2:50 p.m.","3:49 p.m."],
      ["IETAC - ISABELLA","MANCHEGO LOZANO","manc******************@***.com","1 h 47 min","2:01 p.m.","3:48 p.m."],
      ["SG - DANIELA","MANCHOLA TORRES","manc******************@***.com","1 h 44 min","2:05 p.m.","3:49 p.m."],
      ["SG - NICOLLE","MARMOLEJO LUNA","marm****************@***.com","1 h 26 min","2:22 p.m.","3:48 p.m."],
      ["SG - ROSA","MENDIETA FONSECA","mend******************@***.com","1 h 47 min","2:02 p.m.","3:49 p.m."],
      ["SG - JUAN PABLO","MONTOYA ZAPATA","mont******************@***.com","1 h 25 min","2:18 p.m.","3:49 p.m."],
      ["SG - NUBIA LISETH","MORA HERMOZO","mora****************@***.com","1 h 13 min","2:35 p.m.","3:49 p.m."],
      ["SG- SHAROL VANESSA","MORALES OSPINO","mora******************@***.com","1 h 37 min","2:11 p.m.","3:49 p.m."],
      ["IETAC - MARÍA ANGÉLICA","MORELO VILLEROS","more*******************@***.com","42 min","2:37 p.m.","3:45 p.m."],
      ["SG - SOFIA","MÚNERA LÓPEZ","mune***************@***.com","1 h 46 min","2:02 p.m.","3:49 p.m."],
      ["SG - LUIS ANTONIO","MUÑOZ HINCAPIE","muno******************@***.com","1 h 47 min","2:02 p.m.","3:49 p.m."],
      ["Yuleimis","Murillo","muri***********@***.com","1 h 21 min","2:27 p.m.","3:48 p.m."],
      ["SG - JANNA YALID","NORE PÉREZ","nore**************@***.com","1 h 37 min","2:12 p.m.","3:49 p.m."],
      ["SG - ANDRES FELIPE","OROZCO ARRIOLA","oroz******************@***.com","1 h 30 min","2:03 p.m.","3:49 p.m."],
      ["SG - SAMUEL FELIPE","PARRA PULIDO","parr****************@***.com","2 s","2:02 p.m.","2:02 p.m."],
      ["SG - ISABEL SOFIA","PEÑA GARCIA","pena**************@***.com","1 h 16 min","2:19 p.m.","3:35 p.m."],
      ["IETAC - DAYANA MICHEL","PEÑA TORDECILLA","sg.e*********************@***.com","1 h 21 min","2:17 p.m.","3:38 p.m."],
      ["SG - MARÍA PAULA","PÉREZ HORMIGA","sg.e**********************@***.com","1 h 7 min","2:15 p.m.","3:48 p.m."],
      ["IETAC - JORGE ANDRÉS","PÉREZ MESTRA","pere****************@***.com","27 min","2:01 p.m.","2:28 p.m."],
      ["Kevin Santiago","Portillo Benavides","kevi**************************@***.co","1 h 30 min","2:18 p.m.","3:49 p.m."],
      ["SG - JULIO","PRADO BARRIOS","prad****************@***.com","1 h 27 min","2:12 p.m.","3:49 p.m."],
      ["SG - MARGREYS","QUINTERO PALOMINO","quin********************@***.com","1 h 45 min","2:03 p.m.","3:49 p.m."],
      ["camila","ramirez","cami************@***.com","1 h 48 min","2:01 p.m.","3:48 p.m."],
      ["Noraima","Ramírez","rami************@***.com","1 h 44 min","2:04 p.m.","3:48 p.m."],
      ["SG - ROSA INES","REVEROL GONZALEZ","reve*******************@***.com","1 h 45 min","2:03 p.m.","3:48 p.m."],
      ["SG - MIGUEL ANDRÉS","RHENALS ARGUMEDO","rhen********************@***.com","1 h 29 min","2:20 p.m.","3:49 p.m."],
      ["SG - LAURA SOFIA","RIASCOS PANTOJA","rias*******************@***.com","1 h 48 min","2:01 p.m.","3:49 p.m."],
      ["VIVIANA","RINCÓN MARTÍNEZ","vivi**********************@***.com","1 h 49 min","2:00 p.m.","3:49 p.m."],
      ["SG - LORENA ANDREA","RODRÍGUEZ MARTÍNEZ","rodr**********************@***.com","1 h 18 min","2:01 p.m.","3:19 p.m."],
      ["Gerson","Rojas","gers**********@***.com","1 h 43 min","2:06 p.m.","3:49 p.m."],
      ["IETAC - ADRIANA LUCÍA","ROJAS CORDERO","roja*****************@***.com","1 h 42 min","2:07 p.m.","3:49 p.m."],
      ["IETAC - VIVIANA MARCELA","ROMERO ZÚÑIGA","rome*****************@***.com","1 h 43 min","2:06 p.m.","3:49 p.m."],
      ["IETAC - JOHAN ANDRÉS","SALCEDO BEDOYA","salc******************@***.com","1 h 21 min","2:27 p.m.","3:48 p.m."],
      ["IETAC - DAINER ANDRÉS","SÁNCHEZ CASTRO","sanc******************@***.com","1 h 47 min","2:01 p.m.","3:48 p.m."],
      ["SG-VALENTINA","SANDOVAL DIAZ","sand****************@***.com","1 h 45 min","2:03 p.m.","3:48 p.m."],
      ["IETAC - ARNEDIS","SIBAJA BEGAMBRE","siba******************@***.com","1 h 36 min","2:10 p.m.","3:47 p.m."],
      ["SG-ALEX","SIERRA BENÍTEZ","sier*****************@***.com","1 h 41 min","2:07 p.m.","3:49 p.m."],
      ["SG - JOSÉ ÁNGEL","SORA MERCHAN","sora****************@***.com","1 h 47 min","2:01 p.m.","3:48 p.m."],
      ["SG - ANGIE CAROLINA","SOTO GIRALDO","soto****************@***.com","1 h 42 min","2:04 p.m.","3:49 p.m."],
      ["SG - GABRIEL","SUTACHAN MENDEZ","suta******************@***.com","25 min","2:10 p.m.","2:34 p.m."],
      ["Isabella","Tapia","isat********@***.com","1 h 16 min","2:12 p.m.","3:28 p.m."],
      ["SG-MARÍA PAULA","TAPIA YEPES","tapi***************@***.com","3 min","2:19 p.m.","2:25 p.m."],
      ["SG - HANNA NICOLLE","TREJOS APACHE","trej*****************@***.com","1 h 48 min","2:01 p.m.","3:49 p.m."],
      ["SG - JOSE MIGUEL","URREA GÓMEZ","urre***************@***.com","1 h 46 min","2:03 p.m.","3:49 p.m."],
      ["IETAC—ALEXANDRA","URZOLA MARTÍNEZ","urzo******************@***.com","1 h 33 min","2:16 p.m.","3:49 p.m."],
      ["IETAC - ELIANA MARCELA","VERGARA GANDIA","verg******************@***.com","1 h 39 min","2:09 p.m.","3:49 p.m."],
      ["IETAC - LUIS MARIO","ZABALA SÁNCHEZ","zaba******************@***.com","1 h 22 min","2:04 p.m.","3:48 p.m."],
      ["SG - JUAN DIEGO","ZAMBRANO OCAMPO","zamb*******************@***.com","1 h 44 min","2:02 p.m.","3:48 p.m."],
      ["IETAC - RONALDO ANDRÉS","ZULETA GUERRA","zule*****************@***.com","1 h 45 min","2:03 p.m.","3:49 p.m."]
    ]
  },
  {
    id: 4,
    name: "TALLER 8 - CIENCIAS NATURALES",
    program: "PREINTENSIVO - CAL B",
    date: "2026-02-04",
    time: "6:43 p.m. - 8:28 p.m.",
    students: [
      ["SG - DIANA CAROLINA RUIZ","","ruiz*********@***.com","56 min","6:43 p.m.","7:39 p.m."],
      ["SG - SAMARA CARO ORTEGA","","caro*************@***.com","1 h 31 min","6:28 p.m.","8:01 p.m."],
      ["IETAC - MARÍA ESTHER","ACOSTA FERIA","acos****************@***.com","2 h 3 min","6:24 p.m.","8:28 p.m."],
      ["SG - ANGELA VIVIANA","ACOSTA PERAFAN","acos******************@***.com","1 h 59 min","6:28 p.m.","8:28 p.m."],
      ["SG - JOSIAS","ACUÑA ARIAS","acun**************@***.com","42 min","6:36 p.m.","7:18 p.m."],
      ["IETAC - KAREN SOFÍA","ARRIETA VERGARA","arri*******************@***.com","1 h 53 min","6:29 p.m.","8:27 p.m."],
      ["IETAC - CAMILO ANDRÉS","ARROYO CASTRO","arro*****************@***.com","1 h 16 min","6:48 p.m.","8:04 p.m."],
      ["SG - VALERIA","AUSECHA CAMPO","ause****************@***.com","1 h 46 min","6:41 p.m.","8:28 p.m."],
      ["SG - SHEYLA DE JESUS","AVILEZ VEGA","avil***************@***.com","37 min","7:38 p.m.","8:16 p.m."],
      ["SG - MIGUEL ANGEL","AYALA PRIETO","ayal****************@***.com","1 h 59 min","6:28 p.m.","8:28 p.m."],
      ["IETAC - JAIRO MANUEL","BALTAZAR VILLERO","balt********************@***.com","1 h 51 min","6:37 p.m.","8:28 p.m."],
      ["SG - SARA MILETH","BALVIN ARIAS","balv****************@***.com","1 h 57 min","6:30 p.m.","8:27 p.m."],
      ["IETAC - ANA BELÉN","BARÓN CEBALLOS","baro******************@***.com","54 min","6:40 p.m.","8:28 p.m."],
      ["IETAC - LUISA FERNANDA","BARÓN LUCAS","baro***************@***.com","1 h 47 min","6:24 p.m.","8:28 p.m."],
      ["SG - ISABELA","BARREIRO CÁRDENAS","barr*******************@***.com","2 h 3 min","6:24 p.m.","8:28 p.m."],
      ["IETAC - MARIANA DE JESÚS","CABADIA PARRA","caba*****************@***.com","1 h 15 min","7:13 p.m.","8:28 p.m."],
      ["SG - KIARA","CALDERA CORONADO","cald*******************@***.com","1 h 58 min","6:29 p.m.","8:27 p.m."],
      ["SG - MARIA PAULA","CARBALLO QUINTERO","carb******************@***.com","2 h","6:28 p.m.","8:28 p.m."],
      ["IETAC - KAREN DAYANA","CASTILLO PÉREZ","cast******************@***.com","1 h 12 min","7:02 p.m.","8:14 p.m."],
      ["IETAC-Janer","CASTRO MONTALVO","cast******************@***.com","1 h 46 min","6:31 p.m.","8:28 p.m."],
      ["Daginve","Collazos Trujillo","coll********************@***.com","2 h","6:28 p.m.","8:28 p.m."],
      ["IETAC - NEIVER","CORDOBA ARGUMEDO","cord*******************@***.com","2 h","6:28 p.m.","8:28 p.m."],
      ["IETAC - JUAN DAVID","CORREA HERNÁNDEZ","corr********************@***.com","1 h 58 min","6:25 p.m.","8:27 p.m."],
      ["SG - MARÍA JOSÉ","CORTES CHALITAS","cort*******************@***.com","2 h 1 min","6:24 p.m.","8:25 p.m."],
      ["SG - SAMUEL","DIAZ HOYOS","samu******************@***.com","1 h 52 min","6:34 p.m.","8:26 p.m."],
      ["SG - MARIANA","DÍAZ ZÚÑIGA","diaz**************@***.com","1 h 59 min","6:28 p.m.","8:28 p.m."],
      ["IETAC - JHOANS SEBASTIAN","DURANGO ZABALA","dura******************@***.com","2 h 3 min","6:25 p.m.","8:28 p.m."],
      ["SG - LUIS FELIPE","ESCUDERO VILLEGAS","escu*******************@***.com","1 h 48 min","6:40 p.m.","8:28 p.m."],
      ["SG - CRISTIAN DAVID","FAJARDO PERILLA","faja*******************@***.com","1 h 51 min","6:34 p.m.","8:25 p.m."],
      ["IETAC - ELICEO ELI","FUENTES DÍAZ","fuen****************@***.com","42 min","7:46 p.m.","8:28 p.m."],
      ["SG - VALERIE","GAMARRA FONTALVO","gama*******************@***.com","1 h 52 min","6:34 p.m.","8:26 p.m."],
      ["Liz valeria","Gil hoyos","lizv**************@***.com","1 h 51 min","6:37 p.m.","8:28 p.m."],
      ["SG - SOFÍA VALENTINA","GOYES VALLEJO","goye*****************@***.com","1 h 20 min","7:08 p.m.","8:27 p.m."],
      ["SG - ANGIE KATHERINE","GUERRERO CUARAN","guer*******************@***.com","1 h 20 min","7:08 p.m.","8:28 p.m."],
      ["SG - MARIA JOSE","GUTIERREZ OSORIO","guti******************@***.com","1 h 55 min","6:30 p.m.","8:25 p.m."],
      ["SG - LAURA CAMILA","GUZMÁN LÓPEZ","guzm****************@***.com","1 h 40 min","6:47 p.m.","8:28 p.m."],
      ["SG MATHIAS JOSÉ","HERNÁNDEZ BERMÚDEZ","hern****************@***.com","1 h 43 min","6:45 p.m.","8:28 p.m."],
      ["SG - KAMILA INES","HERRERA MARTINEZ","herr*******************@***.com","1 h 59 min","6:28 p.m.","8:27 p.m."],
      ["IETAC - Harold Iván","Hoyos Vergara","hoyo*****************@***.com","2 h 2 min","6:26 p.m.","8:28 p.m."],
      ["IETAC - ALEXANDRA","JULIO ROMERO","juli***************@***.com","1 h 58 min","6:30 p.m.","8:27 p.m."],
      ["Angie","Katherin","angi************@***.com","5 s","7:07 p.m.","7:07 p.m."],
      ["Jhoan David","Leon Lagos","leon*********@***.com","43 s","6:47 p.m.","6:48 p.m."],
      ["SG - EMMA ISABELLA","LINDADO ALGARIN","lind*******************@***.com","2 h 3 min","6:24 p.m.","8:27 p.m."],
      ["SG - SAMUEL","LOAIZA ZAMBRANO","loai******************@***.com","2 h 3 min","6:24 p.m.","8:28 p.m."],
      ["JOSE MANUEL","LONDOÑO LÓPEZ","jose************************@***.com","2 h 4 min","6:24 p.m.","8:28 p.m."],
      ["SG - ALEJANDRO DAVID","LORA TORRES","lora**************@***.com","1 h 39 min","6:24 p.m.","8:28 p.m."],
      ["IETAC - ISABELLA","MANCHEGO LOZANO","manc******************@***.com","1 h 54 min","6:28 p.m.","8:21 p.m."],
      ["SG - DANIELA","MANCHOLA TORRES","manc******************@***.com","2 h 3 min","6:24 p.m.","8:28 p.m."],
      ["SG - NIKOL VANESSA","MANCILLA GONZALEZ","manc*********************@***.com","1 h 59 min","6:28 p.m.","8:28 p.m."],
      ["SG - NICOLLE","MARMOLEJO LUNA","marm****************@***.com","48 min","6:24 p.m.","7:13 p.m."],
      ["SG-LEYSA LUZ","MARTINEZ MENDOZA","mart********************@***.com","1 h 20 min","7:08 p.m.","8:28 p.m."],
      ["SG - ROSA","MENDIETA FONSECA","mend******************@***.com","6 min","6:26 p.m.","6:31 p.m."],
      ["SG - MAVI SOFIA","MICOLTA CARABALI","mico*********************@***.com","2 h 3 min","6:24 p.m.","8:27 p.m."],
      ["SG - JUAN PABLO","MONTOYA ZAPATA","mont******************@***.com","1 h 40 min","6:48 p.m.","8:28 p.m."],
      ["SG - NUBIA LISETH","MORA HERMOZO","mora*************@***.com","2 h 3 min","6:25 p.m.","8:28 p.m."],
      ["SG- SHAROL VANESSA","MORALES OSPINO","mora******************@***.com","12 min","8:01 p.m.","8:25 p.m."],
      ["IETAC - MARÍA ANGÉLICA","MORELO VILLEROS","more*******************@***.com","1 h 42 min","6:37 p.m.","8:28 p.m."],
      ["SG - SOFIA","MÚNERA LÓPEZ","mune***************@***.com","2 h 3 min","6:24 p.m.","8:28 p.m."],
      ["SG - LUIS ANTONIO","MUÑOZ HINCAPIE","muno******************@***.com","2 h","6:28 p.m.","8:28 p.m."],
      ["IETAC - YULEIMIS","MURILLO GÓMEZ","muri****************@***.com","1 h 52 min","6:34 p.m.","8:26 p.m."],
      ["SG - LAURA SOFÍA","OVEJERO MALDONADO","over*********************@***.com","1 h 53 min","6:31 p.m.","8:28 p.m."],
      ["SG - YAMIRA ALEJANDRO","PAEZ CÁCERES","paez****************@***.com","2 h 2 min","6:25 p.m.","8:27 p.m."],
      ["IETAC - HERNÁN ANDRÉS","PALMERA PÉREZ","palm*****************@***.com","1 h 26 min","6:44 p.m.","8:10 p.m."],
      ["IETAC - JORGE ANDRÉS","PÉREZ MESTRA","pere****************@***.com","1 h 47 min","6:29 p.m.","8:16 p.m."],
      ["SG - KEVIN SANTIAGO","PORTILLO BENAVIDES","port********************@***.com","1 h 47 min","6:38 p.m.","8:25 p.m."],
      ["SG - JULIO","PRADO BARRIOS","prad****************@***.com","1 h 47 min","6:24 p.m.","8:28 p.m."],
      ["SG - JAVIER SANTIAGO","PULIDO GONZALEZ","puli*******************@***.com","1 h 59 min","6:28 p.m.","8:28 p.m."],
      ["SG - MARGREYS","QUINTERO PALOMINO","quin********************@***.com","1 h 59 min","6:29 p.m.","8:28 p.m."],
      ["SG - CAMILA ALEJANDRA","RAMIREZ RUEDA","rami*****************@***.com","2 h","6:25 p.m.","8:25 p.m."],
      ["IETAC - DARY LUZ","RAMOS","ramo**********@***.com","1 h 39 min","6:28 p.m.","8:28 p.m."],
      ["SG - DANNA ALEJANDRA","RECALDE RODRÍGUEZ","reca*********************@***.com","1 h 34 min","6:25 p.m.","7:58 p.m."],
      ["SG - ROSA INES","REVEROL GONZALEZ","reve*******************@***.com","2 h 2 min","6:25 p.m.","8:27 p.m."],
      ["SG - MIGUEL ANDRÉS","RHENALS ARGUMEDO","rhen********************@***.com","1 h 52 min","6:34 p.m.","8:26 p.m."],
      ["SG - LAURA SOFIA","RIASCOS PANTOJA","rias*******************@***.com","2 h 3 min","6:25 p.m.","8:28 p.m."],
      ["SG - JUAN SEBASTIAN","RIVERA AVENDAÑO","rive*******************@***.com","3 min","6:45 p.m.","6:47 p.m."],
      ["SG - LORENA ANDREA","RODRÍGUEZ MARTÍNEZ","rodr**********************@***.com","1 h 16 min","6:25 p.m.","7:41 p.m."],
      ["IETAC - SHARON LISHELL","RODRIGUEZ OSORIO","rodr********************@***.com","1 h 48 min","6:40 p.m.","8:28 p.m."],
      ["IETAC - YULISA","RODRÍGUEZ RODRÍGUEZ","rodr**********************@***.com","1 h 59 min","6:28 p.m.","8:27 p.m."],
      ["IETAC - ADRIANA LUCÍA","ROJAS CORDERO","roja*****************@***.com","1 h 52 min","6:30 p.m.","8:28 p.m."],
      ["IETAC - VIVIANA MARCELA","ROMERO ZÚÑIGA","rome*****************@***.com","1 h 1 min","6:28 p.m.","7:30 p.m."],
      ["SG - YESSICA PAOLA","RUIZ RUIZ","ruiz*************@***.com","1 h 54 min","6:34 p.m.","8:28 p.m."],
      ["SG - DANNA VALENTINA","SALAZAR AVIRAMA","sala*******************@***.com","1 h 57 min","6:30 p.m.","8:27 p.m."],
      ["IETAC - JOHAN ANDRÉS","SALCEDO BEDOYA","salc******************@***.com","1 h 56 min","6:29 p.m.","8:25 p.m."],
      ["Melany","Sánchez","mely***********@***.com","2 h 3 min","6:24 p.m.","8:28 p.m."],
      ["IETAC - DAINER ANDRÉS","SÁNCHEZ CASTRO","sanc******************@***.com","1 h 59 min","6:28 p.m.","8:28 p.m."],
      ["SG-VALENTINA","SANDOVAL DIAZ","sand****************@***.com","2 h 3 min","6:24 p.m.","8:28 p.m."],
      ["PREINTENSIVO","SEAMOSGENIOS","seamosgenios@adpmh.com","2 h 4 min","6:23 p.m.","8:28 p.m."],
      ["IETAC - ARNEDIS","SIBAJA BEGAMBRE","siba******************@***.com","1 h 43 min","6:44 p.m.","8:28 p.m."],
      ["SG-ALEX","SIERRA BENÍTEZ","sier*****************@***.com","2 h 1 min","6:25 p.m.","8:28 p.m."],
      ["Nestor Gabriel","Silva Bahamon","silv*****************@***.com","23 min","6:47 p.m.","7:11 p.m."],
      ["SG - JOSÉ ÁNGEL","SORA MERCHAN","sora****************@***.com","1 h 59 min","6:24 p.m.","8:26 p.m."],
      ["SG - GABRIEL","SUTACHAN MENDEZ","suta******************@***.com","2 h 2 min","6:25 p.m.","8:27 p.m."],
      ["SG - ISABELLA","TAPIA ROMERO","tapi***************@***.com","1 h 59 min","6:28 p.m.","8:27 p.m."],
      ["SG-DAYANA MISHEL","TOVIA CHAVEZ","tovi****************@***.com","1 h 56 min","6:31 p.m.","8:28 p.m."],
      ["SG - HANNA NICOLLE","TREJOS APACHE","trej*****************@***.com","2 h 3 min","6:25 p.m.","8:28 p.m."],
      ["SG - JOSE MIGUEL","URREA GÓMEZ","urre***************@***.com","1 h 6 min","7:22 p.m.","8:28 p.m."],
      ["IETAC—ALEXANDRA","URZOLA MARTÍNEZ","urzo******************@***.com","1 h 58 min","6:30 p.m.","8:28 p.m."],
      ["SG - ISABELLA","VÁSQUEZ CASAS","vasq****************@***.com","1 h 53 min","6:35 p.m.","8:28 p.m."],
      ["IETAC - ELIANA MARCELA","VERGARA GANDIA","verg******************@***.com","1 h 59 min","6:28 p.m.","8:28 p.m."],
      ["IETAC - DANIEL ANDRÉS","ZABALA MONTIEL","zaba******************@***.com","1 h 40 min","6:47 p.m.","8:28 p.m."],
      ["IETAC - LUIS MARIO","ZABALA SÁNCHEZ","zaba******************@***.com","1 h 47 min","6:31 p.m.","8:28 p.m."],
      ["SG - JUAN DIEGO","ZAMBRANO OCAMPO","zamb*******************@***.com","1 h 54 min","6:31 p.m.","8:25 p.m."],
      ["Ronaldo","Zuleta","rona*********************@***.com","5 min","6:28 p.m.","6:34 p.m."],
      ["IETAC - RONALDO ANDRÉS","ZULETA GUERRA","zule*****************@***.com","1 h 59 min","6:28 p.m.","8:28 p.m."]
    ]
  },
  {
    id: 5,
    name: "TEÓRICA 12 - MATEMÁTICAS",
    program: "PREICFES INTENSIVO SG",
    date: "2026-02-05",
    time: "2:08 p.m. - 4:04 p.m.",
    students: [
      ["IETAC - MARÍA ESTHER","ACOSTA FERIA","acos****************@***.com","1 h 56 min","2:08 p.m.","4:04 p.m."],
      ["SG - ANGELA VIVIANA","ACOSTA PERAFAN","acos******************@***.com","1 h 56 min","2:07 p.m.","4:04 p.m."],
      ["SG - JOSIAS","ACUÑA ARIAS","acun**************@***.com","18 min","2:10 p.m.","2:28 p.m."],
      ["SG - ANGIE SOFIA","ALDANA ARIAS","alda****************@***.com","36 min","2:03 p.m.","2:39 p.m."],
      ["Yamir","Alejandro","yami*************@***.com","1 h 20 min","2:04 p.m.","4:04 p.m."],
      ["Ximena","Arias","xime***********@***.com","3 min","2:03 p.m.","2:07 p.m."],
      ["IETAC - XIMENA","ARIAS MANCO","aria**************@***.com","1 h 53 min","2:11 p.m.","4:04 p.m."],
      ["IETAC - KAREN SOFÍA","ARRIETA VERGARA","arri*******************@***.com","18 min","2:18 p.m.","2:36 p.m."],
      ["IETAC - CAMILO ANDRÉS","ARROYO CASTRO","arro*****************@***.com","1 h 39 min","2:25 p.m.","4:03 p.m."],
      ["SG - VALERIA","AUSECHA CAMPO","ause****************@***.com","1 h 53 min","2:06 p.m.","3:59 p.m."],
      ["SG - SHEYLA DE JESUS","AVILEZ VEGA","avil***************@***.com","23 min","2:04 p.m.","2:27 p.m."],
      ["SG - MIGUEL ANGEL","AYALA PRIETO","ayal****************@***.com","1 h 6 min","2:17 p.m.","4:01 p.m."],
      ["IETAC - JAIRO MANUEL","BALTAZAR VILLERO","balt********************@***.com","1 h 36 min","2:09 p.m.","3:45 p.m."],
      ["IETAC - ANA BELÉN","BARÓN CEBALLOS","baro******************@***.com","1 h 29 min","2:10 p.m.","3:39 p.m."],
      ["IETAC - LUISA FERNANDA","BARÓN LUCAS","baro***************@***.com","1 h 32 min","2:05 p.m.","4:04 p.m."],
      ["SG - YEIMI PAOLA","BARRAGAN BABILONIA","barr**********************@***.com","1 h 32 min","2:01 p.m.","3:33 p.m."],
      ["SG - ISABELA","BARREIRO CÁRDENAS","barr*******************@***.com","1 h 44 min","2:19 p.m.","4:03 p.m."],
      ["SG - JULIANA","BORJA BUELVAS","borj****************@***.com","1 h","3:04 p.m.","4:03 p.m."],
      ["IETAC - MARIANA DE JESÚS","CABADIA PARRA","caba*****************@***.com","1 h 25 min","2:38 p.m.","4:04 p.m."],
      ["SG - KIARA","CALDERA CORONADO","cald*******************@***.com","47 min","3:12 p.m.","3:59 p.m."],
      ["Oscar Andres","Cano Sanchez","osca*********************@***.com","1 h 55 min","2:09 p.m.","4:04 p.m."],
      ["SG - MARIA PAULA","CARBALLO QUINTERO","carb******************@***.com","2 h 1 min","2:03 p.m.","4:04 p.m."],
      ["SG - MARÍA JULIETH","CASTILLO BAUTISTA","sg.e***********************@***.com","1 h 14 min","2:14 p.m.","3:28 p.m."],
      ["IETAC-Janer","CASTRO MONTALVO","cast******************@***.com","1 h 47 min","2:11 p.m.","3:58 p.m."],
      ["SG - CARLOS ANDRÉS","CHARRIS BONETT","char******************@***.com","47 min","3:09 p.m.","4:04 p.m."],
      ["IETAC - NEIVER","CORDOBA ARGUMEDO","cord*******************@***.com","1 h 55 min","2:07 p.m.","4:02 p.m."],
      ["IETAC - JUAN DAVID","CORREA HERNÁNDEZ","corr********************@***.com","1 h 53 min","2:10 p.m.","4:04 p.m."],
      ["SG - MARÍA JOSÉ","CORTES CHALITAS","cort*******************@***.com","17 min","2:56 p.m.","3:13 p.m."],
      ["SG - CAMILO ANDRES","COTES","cote*****@***.com","59 min","3:05 p.m.","4:04 p.m."],
      ["SG - CRISTIAN DE JESUS","CUESTA BLANQUICETT","cues******************@***.com","1 h 34 min","2:20 p.m.","4:04 p.m."],
      ["SG - SAMUEL","DIAZ HOYOS","samu******************@***.com","1 h 46 min","2:04 p.m.","4:04 p.m."],
      ["SG - MARIANA","DÍAZ ZÚÑIGA","diaz**************@***.com","1 h 58 min","2:05 p.m.","4:04 p.m."],
      ["IETAC - JHOANS SEBASTIAN","DURANGO ZABALA","dura******************@***.com","2 h 2 min","2:01 p.m.","4:03 p.m."],
      ["SG - JUAN ANDRES","ECHEVERRÍA ESCOBAR","eche********************@***.com","1 h 53 min","2:10 p.m.","4:04 p.m."],
      ["Christopher","Erazo","chri******************@***.com","1 h 18 min","2:23 p.m.","4:04 p.m."],
      ["Luis Felipe","Escudero Villegas","luis************@***.com","6 min","2:32 p.m.","2:39 p.m."],
      ["SG - LUIS FELIPE","ESCUDERO VILLEGAS","escu*******************@***.com","1 h 12 min","2:51 p.m.","4:04 p.m."],
      ["SG - SARA SOFIA","ESQUIVEL VARGAS","esqu*******************@***.com","1 h 53 min","2:10 p.m.","4:03 p.m."],
      ["SG-TALIANA ANDREA","FLOREZ SALGADO","flor******************@***.com","1 h 43 min","2:05 p.m.","3:48 p.m."],
      ["SG - DANIELA SOFÍA","FLOREZ VARGAS","flor*****************@***.com","1 h 38 min","2:09 p.m.","3:48 p.m."],
      ["IETAC - ELICEO ELI","FUENTES DÍAZ","fuen****************@***.com","","2:34 p.m.","3:22 p.m."],
      ["SG - VALERIE","GAMARRA FONTALVO","gama*******************@***.com","1 h 47 min","2:12 p.m.","3:58 p.m."],
      ["SG - ÁNGEL GABRIEL","GÓMEZ","gome**********@***.com","2 min","3:07 p.m.","3:09 p.m."],
      ["SG - LAURA MADELEINE","GÓMEZ SUÁREZ","gome****************@***.com","1 h 50 min","2:07 p.m.","4:00 p.m."],
      ["SG - MARIA JOSE","GUTIERREZ OSORIO","guti******************@***.com","1 h 25 min","2:03 p.m.","3:28 p.m."],
      ["SG - LAURA CAMILA","GUZMÁN LÓPEZ","guzm****************@***.com","1 h 13 min","2:47 p.m.","3:59 p.m."],
      ["Yancarlos","Hernandez casianis","yanc**********************@***.com","1 h 54 min","2:02 p.m.","4:00 p.m."],
      ["IETAC - Harold Iván","Hoyos Vergara","hoyo*****************@***.com","2 h 2 min","2:01 p.m.","4:04 p.m."],
      ["SG - JHOAN DAVID","LEÓN LAGOS","leon**************@***.com","1 min","3:21 p.m.","3:22 p.m."],
      ["SG - EMMA ISABELLA","LINDADO ALGARIN","lind*******************@***.com","2 h 1 min","2:01 p.m.","4:03 p.m."],
      ["SG - SAMUEL","LOAIZA ZAMBRANO","loai******************@***.com","2 h","2:04 p.m.","4:04 p.m."],
      ["SG-LEYSA LUZ","MARTINEZ MENDOZA","mart********************@***.com","1 h 27 min","2:37 p.m.","4:03 p.m."],
      ["SG - ROSA","MENDIETA FONSECA","mend******************@***.com","1 h 59 min","2:04 p.m.","4:04 p.m."],
      ["IETAC - LUIS DANIEL","MENDOZA URIBE","mend*****************@***.com","1 h 32 min","2:09 p.m.","3:40 p.m."],
      ["SG - MAVI SOFIA","MICOLTA CARABALI","mico*********************@***.com","1 h 13 min","2:32 p.m.","3:45 p.m."],
      ["SG - NUBIA LISETH","MORA HERMOZO","mora****************@***.com","8 min","2:02 p.m.","2:10 p.m."],
      ["SG - NUBIA LISETH","MORA HERMOZO","mora*************@***.com","1 h 55 min","2:09 p.m.","4:04 p.m."],
      ["IETAC - MARÍA ANGÉLICA","MORELO VILLEROS","more*******************@***.com","1 h 48 min","2:16 p.m.","4:04 p.m."],
      ["SG - LUIS ANTONIO","MUÑOZ HINCAPIE","muno******************@***.com","1 h 48 min","2:15 p.m.","4:03 p.m."],
      ["IETAC - YULEIMIS","MURILLO GÓMEZ","muri****************@***.com","1 h 54 min","2:06 p.m.","4:00 p.m."],
      ["SG - ANDRES FELIPE","OROZCO ARRIOLA","oroz******************@***.com","1 h 49 min","2:15 p.m.","4:04 p.m."],
      ["SG - SAMUEL FELIPE","PARRA PULIDO","parr****************@***.com","1 h 49 min","2:09 p.m.","3:58 p.m."],
      ["IETAC - DAYANA MICHEL","PEÑA TORDECILLA","sg.e*********************@***.com","2 h","2:03 p.m.","4:04 p.m."],
      ["María","Pérez","mapi********@***.com","43 s","2:14 p.m.","2:14 p.m."],
      ["MARÍA PAULA","PÉREZ HORMIGA","pere*****************@***.com","1 h 50 min","2:07 p.m.","4:01 p.m."],
      ["SG - JULIO","PRADO BARRIOS","prad****************@***.com","1 h 38 min","2:12 p.m.","3:49 p.m."],
      ["SG - JAVIER SANTIAGO","PULIDO GONZALEZ","puli*******************@***.com","1 h 47 min","2:15 p.m.","4:02 p.m."],
      ["IETAC - DARY LUZ","RAMOS","ramo**********@***.com","1 h 47 min","2:05 p.m.","4:04 p.m."],
      ["SG - DANNA ALEJANDRA","RECALDE RODRÍGUEZ","reca*********************@***.com","1 h 17 min","2:16 p.m.","3:33 p.m."],
      ["SG - MIGUEL ANDRÉS","RHENALS ARGUMEDO","rhen********************@***.com","33 min","3:31 p.m.","4:04 p.m."],
      ["SG - LAURA SOFIA","RIASCOS PANTOJA","rias*******************@***.com","2 h 1 min","2:03 p.m.","4:04 p.m."],
      ["VIVIANA","RINCÓN MARTÍNEZ","vivi**********************@***.com","2 h 3 min","2:01 p.m.","4:04 p.m."],
      ["IETAC - SHARON LISHELL","RODRIGUEZ OSORIO","rodr********************@***.com","2 h 1 min","2:02 p.m.","4:03 p.m."],
      ["IETAC - YULISA","RODRÍGUEZ RODRÍGUEZ","rodr**********************@***.com","1 h 58 min","2:05 p.m.","4:04 p.m."],
      ["IETAC - ADRIANA LUCÍA","ROJAS CORDERO","roja*****************@***.com","1 h 39 min","2:11 p.m.","4:04 p.m."],
      ["SG - YESSICA PAOLA","RUIZ RUIZ","ruiz*************@***.com","1 h 19 min","2:44 p.m.","4:04 p.m."],
      ["SG - DANNA VALENTINA","SALAZAR AVIRAMA","sala*******************@***.com","1 h 57 min","2:04 p.m.","4:02 p.m."],
      ["IETAC - JOHAN ANDRÉS","SALCEDO BEDOYA","salc******************@***.com","1 h 48 min","2:15 p.m.","4:04 p.m."],
      ["Melany","Sánchez","mely***********@***.com","1 h 56 min","2:07 p.m.","4:04 p.m."],
      ["IETAC - DAINER ANDRÉS","SÁNCHEZ CASTRO","sanc******************@***.com","1 h 50 min","2:08 p.m.","3:59 p.m."],
      ["SG-VALENTINA","SANDOVAL DIAZ","sand****************@***.com","1 h 55 min","2:02 p.m.","3:57 p.m."],
      ["MARIA FERNANDA","SANTANA RAMIREZ","mari**************************@***.com","1 h 39 min","2:17 p.m.","4:00 p.m."],
      ["SG - MARÍA FERNANDA","SANTANA RAMÍREZ","sant*******************@***.com","4 min","2:05 p.m.","2:09 p.m."],
      ["SG-ALEX","SIERRA BENÍTEZ","sier*****************@***.com","2 h","2:02 p.m.","4:04 p.m."],
      ["SG - JOSÉ ÁNGEL","SORA MERCHAN","sora****************@***.com","2 h 2 min","2:01 p.m.","4:04 p.m."],
      ["SG - ANGIE CAROLINA","SOTO GIRALDO","soto****************@***.com","1 h 29 min","2:01 p.m.","3:31 p.m."],
      ["Samir","Suarez","suar***********@***.com","27 s","2:11 p.m.","2:12 p.m."],
      ["SG - GABRIEL","SUTACHAN MENDEZ","suta******************@***.com","2 h 2 min","2:02 p.m.","4:03 p.m."],
      ["isa","tapia","isab***********@***.com","1 h 49 min","2:11 p.m.","4:00 p.m."],
      ["SG - HANNA NICOLLE","TREJOS APACHE","trej*****************@***.com","1 h 42 min","2:22 p.m.","4:04 p.m."],
      ["Luis","Uribe","ieta*****************@***.com","36 s","2:07 p.m.","2:07 p.m."],
      ["SG - JOSE MIGUEL","URREA GÓMEZ","urre***************@***.com","1 h 7 min","2:54 p.m.","4:03 p.m."],
      ["IETAC—ALEXANDRA","URZOLA MARTÍNEZ","urzo******************@***.com","1 h 53 min","2:09 p.m.","4:04 p.m."],
      ["SG - ISABELLA","VÁSQUEZ CASAS","vasq****************@***.com","1 h 46 min","2:17 p.m.","4:04 p.m."],
      ["IETAC - ELIANA MARCELA","VERGARA GANDIA","verg******************@***.com","1 h 15 min","2:14 p.m.","3:38 p.m."],
      ["IETAC - DANIEL ANDRÉS","ZABALA MONTIEL","zaba******************@***.com","2 h 2 min","2:02 p.m.","4:03 p.m."],
      ["IETAC - LUIS MARIO","ZABALA SÁNCHEZ","zaba******************@***.com","1 h 38 min","2:24 p.m.","4:02 p.m."],
      ["SG - JUAN DIEGO","ZAMBRANO OCAMPO","zamb*******************@***.com","1 h 57 min","2:07 p.m.","4:03 p.m."],
      ["IETAC - RONALDO ANDRÉS","ZULETA GUERRA","zule*****************@***.com","2 h 1 min","2:03 p.m.","4:04 p.m."]
    ]
  },
  {
    id: 6,
    name: "TEXTOS DISCONTINUOS - LECTURA CRÍTICA",
    program: "PREINTENSIVO - CAL B",
    date: "2026-01-22",
    time: "8:14 p.m. - 9:26 p.m.",
    students: [
      ["SG - DIANA CAROLINA RUIZ","","ruiz*********@***.com","2 h 14 min","8:14 p.m.","10:28 p.m."],
      ["SG - SAMARA CARO ORTEGA","","caro*************@***.com","2 h 18 min","8:10 p.m.","10:29 p.m."],
      ["IETAC - MARÍA ESTHER","ACOSTA FERIA","acos****************@***.com","2 h 11 min","8:10 p.m.","10:20 p.m."],
      ["SG - ANGELA VIVIANA","ACOSTA PERAFAN","acos******************@***.com","1 h 47 min","8:09 p.m.","9:56 p.m."],
      ["SG - JOSIAS","ACUÑA ARIAS","acun**************@***.com","2 h 18 min","8:08 p.m.","10:26 p.m."],
      ["HELLEN SOFIA","ARANDA TOVAR","hell********************@***.com","2 h 29 min","8:00 p.m.","10:29 p.m."],
      ["SG - KAREN YULIED","ARENAS COMETA","aren*****************@***.com","1 h 55 min","8:01 p.m.","9:56 p.m."],
      ["IETAC - CAMILO ANDRÉS","ARROYO CASTRO","arro*****************@***.com","5 min","8:31 p.m.","8:35 p.m."],
      ["SG - VALERIA","AUSECHA CAMPO","ause****************@***.com","1 h 46 min","8:03 p.m.","9:48 p.m."],
      ["SG - SHEYLA DE JESUS","AVILEZ VEGA","avil***************@***.com","2 h 24 min","8:04 p.m.","10:29 p.m."],
      ["SG - MIGUEL ANGEL","AYALA PRIETO","ayal****************@***.com","54 min","8:02 p.m.","8:57 p.m."],
      ["SG - ISABELA","BARREIRO CÁRDENAS","barr*******************@***.com","58 min","8:09 p.m.","9:08 p.m."],
      ["IETAC - MARIANA DE JESÚS","CABADIA PARRA","caba*****************@***.com","2 h 4 min","8:08 p.m.","10:14 p.m."],
      ["SG - KIARA","CALDERA CORONADO","cald*******************@***.com","1 h 43 min","8:03 p.m.","9:45 p.m."],
      ["SG - HILAYDA ROSA","CANTILLO RUZ","cant****************@***.com","2 h 5 min","8:02 p.m.","10:08 p.m."],
      ["SG - MARIA PAULA","CARBALLO QUINTERO","carb******************@***.com","1 h 44 min","8:09 p.m.","9:53 p.m."],
      ["SG - MARÍA JULIETH","CASTILLO BAUTISTA","sg.e***********************@***.com","46 min","9:23 p.m.","10:09 p.m."],
      ["SG - CARLOS ANDRÉS","CHARRIS BONETT","char******************@***.com","1 h 18 min","9:10 p.m.","10:29 p.m."],
      ["IETAC - JUAN DAVID","CORREA HERNÁNDEZ","corr********************@***.com","2 h 3 min","8:04 p.m.","10:07 p.m."],
      ["SG - MARÍA JOSÉ","CORTES CHALITAS","cort*******************@***.com","1 h 16 min","8:34 p.m.","9:49 p.m."],
      ["SG - CRISTIAN DE JESUS","CUESTA BLANQUICETT","cues******************@***.com","1 h 27 min","8:09 p.m.","9:36 p.m."],
      ["SG - SAMUEL","DIAZ HOYOS","samu******************@***.com","1 h 52 min","8:01 p.m.","9:53 p.m."],
      ["Juan","Echeverría escobar","juan*******@***.com","2 s","8:06 p.m.","8:06 p.m."],
      ["SG - JUAN ANDRES","ECHEVERRÍA ESCOBAR","eche********************@***.com","2 h 21 min","8:08 p.m.","10:29 p.m."],
      ["SG - LUIS FELIPE","ESCUDERO VILLEGAS","escu*******************@***.com","1 h 22 min","8:26 p.m.","9:50 p.m."],
      ["Sara","Esquivel Vargas","sara*****************@***.com","3 min","8:03 p.m.","8:06 p.m."],
      ["SG - SARA SOFIA","ESQUIVEL VARGAS","esqu*******************@***.com","2 h 21 min","8:07 p.m.","10:28 p.m."],
      ["SG - CRISTIAN DAVID","FAJARDO PERILLA","faja*******************@***.com","1 h 30 min","8:00 p.m.","9:31 p.m."],
      ["SG - DANIELA SOFÍA","FLOREZ VARGAS","flor*****************@***.com","1 h 24 min","8:02 p.m.","9:26 p.m."],
      ["SG - CAMILO ANDRES","FUKEN MENDEZ","fuke****************@***.com","1 h 31 min","8:49 p.m.","10:28 p.m."],
      ["SG - VALERIE","GAMARRA FONTALVO","gama*******************@***.com","1 h 40 min","8:16 p.m.","9:56 p.m."],
      ["SG - SOFÍA VALENTINA","GOYES VALLEJO","goye*****************@***.com","1 h 55 min","8:00 p.m.","9:55 p.m."],
      ["SG - MARIA JOSE","GUTIERREZ OSORIO","guti******************@***.com","1 h 26 min","8:12 p.m.","9:39 p.m."],
      ["SG MATHIAS JOSÉ","HERNÁNDEZ BERMÚDEZ","hern****************@***.com","1 h 52 min","8:08 p.m.","10:00 p.m."],
      ["IETAC - Harold Iván","Hoyos Vergara","hoyo*****************@***.com","2 h","8:00 p.m.","10:00 p.m."],
      ["SG - JHOAN DAVID","LEÓN LAGOS","leon**************@***.com","44 min","8:05 p.m.","8:49 p.m."],
      ["SG - EMMA ISABELLA","LINDADO ALGARIN","lind*******************@***.com","2 h 27 min","8:00 p.m.","10:27 p.m."],
      ["SG - SAMUEL","LOAIZA ZAMBRANO","loai******************@***.com","2 h 25 min","8:04 p.m.","10:29 p.m."],
      ["Andrés","López","andr************@***.com","4 min","8:01 p.m.","8:06 p.m."],
      ["SG - DIANA MARCELA","MANBUSCAY AGUDELO","manb******************@***.com","1 h 58 min","8:27 p.m.","10:24 p.m."],
      ["SG - DANIELA","MANCHOLA TORRES","manc******************@***.com","2 h 25 min","8:03 p.m.","10:28 p.m."],
      ["SG - NICOLLE","MARMOLEJO LUNA","marm****************@***.com","1 h 25 min","8:12 p.m.","9:36 p.m."],
      ["SG-LEYSA LUZ","MARTINEZ MENDOZA","mart********************@***.com","2 h 16 min","8:12 p.m.","10:28 p.m."],
      ["SG - ROSA","MENDIETA FONSECA","mend******************@***.com","2 h 26 min","8:02 p.m.","10:29 p.m."],
      ["IETAC - LUIS DANIEL","MENDOZA URIBE","mend*****************@***.com","1 h 45 min","8:05 p.m.","9:49 p.m."],
      ["SG - JESUS IVAN","MIRANDA VARELO","mira******************@***.com","2 h 22 min","8:07 p.m.","10:29 p.m."],
      ["SG - JUAN PABLO","MONTOYA ZAPATA","mont******************@***.com","1 h 55 min","8:34 p.m.","10:29 p.m."],
      ["SG - NUBIA LISETH","MORA HERMOZO","mora****************@***.com","2 h 26 min","8:02 p.m.","10:28 p.m."],
      ["SG- SHAROL VANESSA","MORALES OSPINO","mora******************@***.com","48 min","8:01 p.m.","9:17 p.m."],
      ["IETAC - MARÍA ANGÉLICA","MORELO VILLEROS","more*******************@***.com","41 min","8:14 p.m.","8:56 p.m."],
      ["SG - SOFIA","MÚNERA LÓPEZ","mune***************@***.com","2 h 27 min","8:02 p.m.","10:29 p.m."],
      ["SG - LUIS ANTONIO","MUÑOZ HINCAPIE","muno******************@***.com","1 h 33 min","8:19 p.m.","9:52 p.m."],
      ["SG - JANNA YALID","NORE PÉREZ","nore**************@***.com","2 h 21 min","8:07 p.m.","10:28 p.m."],
      ["SG - ANDRES FELIPE","OROZCO ARRIOLA","oroz******************@***.com","2 h 13 min","8:05 p.m.","10:20 p.m."],
      ["IETAC - DAVIER ESTEBAN","OTERO URANGO","oter*****************@***.com","21 min","9:33 p.m.","9:55 p.m."],
      ["SG - ISABEL SOFIA","PEÑA GARCIA","pena**************@***.com","2 min","8:27 p.m.","8:28 p.m."],
      ["SG - MARÍA PAULA","PÉREZ HORMIGA","sg.e**********************@***.com","1 h 32 min","8:08 p.m.","9:40 p.m."],
      ["SG - DARLY SARAY","PÉREZ JAIMES","pere****************@***.com","1 h 42 min","8:04 p.m.","9:46 p.m."],
      ["SG - JULIO","PRADO BARRIOS","prad****************@***.com","1 h 48 min","8:10 p.m.","9:59 p.m."],
      ["SG - JAVIER SANTIAGO","PULIDO GONZALEZ","puli*******************@***.com","2 h 14 min","8:02 p.m.","10:16 p.m."],
      ["SG - MARGREYS","QUINTERO PALOMINO","quin********************@***.com","1 h 2 min","8:02 p.m.","9:19 p.m."],
      ["SG - CAMILA ALEJANDRA","RAMIREZ RUEDA","rami*****************@***.com","2 h 10 min","8:04 p.m.","10:14 p.m."],
      ["SG - DAVID SANTIAGO","RAMÍREZ SALGADO","rami*******************@***.com","1 h 30 min","8:06 p.m.","9:36 p.m."],
      ["SG - DANNA ALEJANDRA","RECALDE RODRÍGUEZ","reca*********************@***.com","1 h 48 min","8:08 p.m.","9:56 p.m."],
      ["SG - ROSA INES","REVEROL GONZALEZ","reve*******************@***.com","2 h 25 min","8:00 p.m.","10:26 p.m."],
      ["SG - MIGUEL ANDRÉS","RHENALS ARGUMEDO","rhen********************@***.com","1 h 45 min","8:08 p.m.","9:53 p.m."],
      ["SG - LAURA SOFIA","RIASCOS PANTOJA","rias*******************@***.com","2 h 23 min","8:05 p.m.","10:28 p.m."],
      ["SG - JUAN SEBASTIAN","RIVERA AVENDAÑO","rive*******************@***.com","15 min","8:12 p.m.","8:29 p.m."],
      ["SG - GERSON GIOVANI","ROJAS PISSO","roja**************@***.com","41 min","9:12 p.m.","9:53 p.m."],
      ["SG - YESSICA PAOLA","RUIZ RUIZ","ruiz*************@***.com","2 h 24 min","8:04 p.m.","10:29 p.m."],
      ["IETAC - JOHAN ANDRÉS","SALCEDO BEDOYA","salc******************@***.com","1 h 43 min","8:15 p.m.","9:58 p.m."],
      ["SG-VALENTINA","SANDOVAL DIAZ","sand****************@***.com","2 h 3 min","8:01 p.m.","10:03 p.m."],
      ["IETAC - ARNEDIS","SIBAJA BEGAMBRE","siba******************@***.com","1 h 22 min","8:54 p.m.","10:25 p.m."],
      ["SG-ALEX","SIERRA BENÍTEZ","sier*****************@***.com","2 h 26 min","8:02 p.m.","10:28 p.m."],
      ["Nestor Gabriel","Silva Bahamon","nsil*********@***.com","4 min","8:02 p.m.","8:06 p.m."],
      ["SG - JOSÉ ÁNGEL","SORA MERCHAN","sora****************@***.com","1 h 39 min","8:00 p.m.","9:39 p.m."],
      ["SG - GABRIEL","SUTACHAN MENDEZ","suta******************@***.com","2 h 8 min","8:08 p.m.","10:19 p.m."],
      ["SG - ISABELLA","TAPIA ROMERO","tapi***************@***.com","1 h 31 min","8:08 p.m.","9:39 p.m."],
      ["SG-MARÍA PAULA","TAPIA YEPES","tapi***************@***.com","1 h 11 min","8:07 p.m.","9:37 p.m."],
      ["SG - HANNA NICOLLE","TREJOS APACHE","trej*****************@***.com","1 h 53 min","8:03 p.m.","9:56 p.m."],
      ["SG - JOSE MIGUEL","URREA GÓMEZ","urre***************@***.com","2 h 28 min","8:00 p.m.","10:29 p.m."],
      ["IETAC—ALEXANDRA","URZOLA MARTÍNEZ","urzo******************@***.com","1 h 8 min","8:35 p.m.","9:53 p.m."],
      ["IETAC - ELIANA MARCELA","VERGARA GANDIA","verg******************@***.com","17 min","8:12 p.m.","8:29 p.m."],
      ["SG - JUAN DIEGO","ZAMBRANO OCAMPO","zamb*******************@***.com","1 h 31 min","8:04 p.m.","9:36 p.m."],
      ["IETAC - RONALDO ANDRÉS","ZULETA GUERRA","zule*****************@***.com","1 h 9 min","8:04 p.m.","9:26 p.m."]
    ]
  }
];